// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenThiKhanhLy_424.Data;

#nullable disable

namespace NguyenThiKhanhLy_424.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240615100808_Creater_table_Lophoc")]
    partial class Creater_table_Lophoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("NguyenThiKhanhLy_424.Lophoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTT")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenLop")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaLop");

                    b.ToTable("Lophocs");
                });
#pragma warning restore 612, 618
        }
    }
}
