// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenThiKhanhLy_424.Data;

#nullable disable

namespace NguyenThiKhanhLy_424.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240617101708_Create_table_Employee")]
    partial class Create_table_Employee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("NguyenThiKhanhLy_424.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NguyenThiKhanhLy_424.Models.Employee", b =>
                {
                    b.HasBaseType("NguyenThiKhanhLy_424.Person");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("NguyenThiKhanhLy_424.Models.Employee", b =>
                {
                    b.HasOne("NguyenThiKhanhLy_424.Person", null)
                        .WithOne()
                        .HasForeignKey("NguyenThiKhanhLy_424.Models.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
