// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenThiKhanhLy_424.Data;

#nullable disable

namespace NguyenThiKhanhLy_424.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("NguyenThiKhanhLy_424.Lophoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoTT")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenLop")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaLop");

                    b.ToTable("Lophocs");
                });
#pragma warning restore 612, 618
        }
    }
}
